import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'SchoolFlow API',
      version: '1.0.0',
      description: 'API documentation for SchoolFlow - School Management Platform',
      contact: {
        name: 'SchoolFlow Team',
        email: 'support@schoolflow.io',
      },
      license: {
        name: 'MIT',
        url: 'https://opensource.org/licenses/MIT',
      },
    },
    servers: [
      {
        url: '/api/v1',
        description: 'API v1 (relative path)',
      },
      {
        url: 'http://localhost:4000/api/v1',
        description: 'Local Development Server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT token obtained from /auth/login or /auth/register',
        },
        cookieAuth: {
          type: 'apiKey',
          in: 'cookie',
          name: 'sf_token',
          description: 'HttpOnly cookie set after login',
        },
      },
      schemas: {
        // Common schemas
        Error: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            error: { type: 'string', example: 'Error message' },
            code: { type: 'string', example: 'ERROR_CODE' },
          },
        },
        Success: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            data: { type: 'object' },
          },
        },
        PaginatedResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            data: {
              type: 'object',
              properties: {
                items: { type: 'array', items: { type: 'object' } },
                total: { type: 'integer', example: 100 },
                page: { type: 'integer', example: 1 },
                pages: { type: 'integer', example: 5 },
              },
            },
          },
        },
        // Auth schemas
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string', format: 'email', example: 'admin@school.com' },
            password: { type: 'string', format: 'password', example: 'password123' },
          },
        },
        RegisterRequest: {
          type: 'object',
          required: ['schoolName', 'firstName', 'lastName', 'email', 'password'],
          properties: {
            schoolName: { type: 'string', example: 'École Primaire' },
            firstName: { type: 'string', example: 'Jean' },
            lastName: { type: 'string', example: 'Dupont' },
            email: { type: 'string', format: 'email', example: 'admin@school.com' },
            password: { type: 'string', format: 'password', example: 'password123' },
            phone: { type: 'string', example: '+33123456789' },
            acceptTerms: { type: 'boolean', example: true },
          },
        },
        AuthResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            data: {
              type: 'object',
              properties: {
                token: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIs...' },
                mustChangePassword: { type: 'boolean', example: false },
                user: { $ref: '#/components/schemas/User' },
                workspace: { $ref: '#/components/schemas/School' },
              },
            },
          },
        },
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            email: { type: 'string', format: 'email' },
            name: { type: 'string' },
            role: { type: 'string' },
            phone: { type: 'string', nullable: true },
            avatar: { type: 'string', nullable: true },
            isActive: { type: 'boolean' },
            status: { type: 'string', enum: ['active', 'suspended', 'disabled', 'archived'] },
            mustChangePassword: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        School: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            slug: { type: 'string' },
            address: { type: 'string' },
            phone: { type: 'string' },
            email: { type: 'string', format: 'email' },
            logo: { type: 'string' },
            currency: { type: 'string', example: 'USD' },
            academicYear: { type: 'string', example: '2025-2026' },
            director: { type: 'string' },
            settings: { type: 'object' },
          },
        },
        Student: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', example: 'SCF-2025-00001' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            dateOfBirth: { type: 'string', format: 'date' },
            gender: { type: 'string', enum: ['M', 'F'] },
            classId: { type: 'string', format: 'uuid', nullable: true },
            class: { $ref: '#/components/schemas/Class' },
            phone: { type: 'string' },
            email: { type: 'string', format: 'email' },
            address: { type: 'string' },
            parentName: { type: 'string' },
            parentPhone: { type: 'string' },
            parentEmail: { type: 'string', format: 'email' },
            notes: { type: 'string' },
            photo: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['active', 'inactive', 'archived'] },
            enrollmentDate: { type: 'string', format: 'date' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Teacher: {
          allOf: [
            { $ref: '#/components/schemas/User' },
            {
              type: 'object',
              properties: {
                subjects: {
                  type: 'array',
                  items: { $ref: '#/components/schemas/Subject' },
                },
                classes: {
                  type: 'array',
                  items: { $ref: '#/components/schemas/Class' },
                },
              },
            },
          ],
        },
        Class: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            level: { type: 'string' },
            section: { type: 'string' },
            capacity: { type: 'integer' },
            teacherId: { type: 'string', format: 'uuid', nullable: true },
            teacher: { $ref: '#/components/schemas/User' },
            academicYear: { type: 'string' },
            schoolId: { type: 'string', format: 'uuid' },
            students: {
              type: 'array',
              items: { $ref: '#/components/schemas/Student' },
            },
            subjects: {
              type: 'array',
              items: { $ref: '#/components/schemas/Subject' },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Subject: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            code: { type: 'string' },
            coefficient: { type: 'number' },
            department: { type: 'string' },
            classId: { type: 'string', format: 'uuid' },
            class: { $ref: '#/components/schemas/Class' },
            teacherId: { type: 'string', format: 'uuid', nullable: true },
            teacher: { $ref: '#/components/schemas/User' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Grade: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            student: { $ref: '#/components/schemas/Student' },
            subjectId: { type: 'string', format: 'uuid' },
            subject: { $ref: '#/components/schemas/Subject' },
            examType: { type: 'string', example: 'exam' },
            examName: { type: 'string', example: 'Contrôle 1' },
            score: { type: 'number', minimum: 0, maximum: 20 },
            coefficient: { type: 'number', minimum: 1, default: 1 },
            term: { type: 'integer', minimum: 1, maximum: 3 },
            academicYear: { type: 'string' },
            date: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['DRAFT', 'SUBMITTED', 'VALIDATED', 'PUBLISHED'] },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Attendance: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            student: { $ref: '#/components/schemas/Student' },
            classId: { type: 'string', format: 'uuid' },
            class: { $ref: '#/components/schemas/Class' },
            date: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['present', 'absent', 'late', 'excused'] },
            notes: { type: 'string' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Fee: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            student: { $ref: '#/components/schemas/Student' },
            type: { type: 'string', enum: ['tuition', 'registration', 'exam', 'transport', 'canteen', 'uniform', 'other'] },
            amount: { type: 'number' },
            totalAmount: { type: 'number' },
            paidAmount: { type: 'number', default: 0 },
            balance: { type: 'number' },
            dueDate: { type: 'string', format: 'date' },
            academicYear: { type: 'string' },
            term: { type: 'integer', minimum: 1, maximum: 3 },
            status: { type: 'string', enum: ['pending', 'paid', 'partial', 'overdue'] },
            installments: { type: 'integer', default: 1 },
            notes: { type: 'string' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Payment: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            studentId: { type: 'string', format: 'uuid' },
            student: { $ref: '#/components/schemas/Student' },
            feeId: { type: 'string', format: 'uuid', nullable: true },
            fee: { $ref: '#/components/schemas/Fee' },
            amount: { type: 'number' },
            currency: { type: 'string', example: 'USD' },
            amountInBase: { type: 'number' },
            exchangeRate: { type: 'number', nullable: true },
            rateSource: { type: 'string', nullable: true },
            method: { type: 'string', enum: ['cash', 'bank', 'transfer', 'other'] },
            reference: { type: 'string' },
            notes: { type: 'string' },
            date: { type: 'string', format: 'date-time' },
            receivedById: { type: 'string', format: 'uuid' },
            receivedBy: { $ref: '#/components/schemas/User' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        DocumentTemplate: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            description: { type: 'string' },
            category: { type: 'string', enum: ['bulletin', 'certificat', 'billet_vacances', 'avis_parents', 'document_administratif', 'financier', 'autre'] },
            format: { type: 'string', enum: ['A4', 'A5', 'A6', 'Letter', 'Legal', 'custom'] },
            orientation: { type: 'string', enum: ['portrait', 'landscape'] },
            status: { type: 'string', enum: ['brouillon', 'actif', 'archive'] },
            version: { type: 'integer' },
            schema: { type: 'object' },
            scope: { type: 'object' },
            creatorId: { type: 'string', format: 'uuid' },
            creator: { $ref: '#/components/schemas/User' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        GeneratedDocument: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            templateId: { type: 'string', format: 'uuid' },
            template: { $ref: '#/components/schemas/DocumentTemplate' },
            documentType: { type: 'string' },
            studentId: { type: 'string', format: 'uuid', nullable: true },
            student: { $ref: '#/components/schemas/Student' },
            filePath: { type: 'string' },
            title: { type: 'string' },
            documentNumber: { type: 'string' },
            status: { type: 'string', enum: ['DRAFT', 'GENERATED', 'REVIEWED', 'VALIDATED', 'PUBLISHED', 'ARCHIVED', 'REVOKED'] },
            metadata: { type: 'object' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Announcement: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            title: { type: 'string' },
            content: { type: 'string' },
            audience: { type: 'string', enum: ['all', 'teachers', 'parents', 'students', 'staff'] },
            classId: { type: 'string', format: 'uuid', nullable: true },
            class: { $ref: '#/components/schemas/Class' },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            authorId: { type: 'string', format: 'uuid' },
            author: { $ref: '#/components/schemas/User' },
            publishedAt: { type: 'string', format: 'date-time', nullable: true },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            user: { $ref: '#/components/schemas/User' },
            type: { type: 'string' },
            title: { type: 'string' },
            message: { type: 'string' },
            isRead: { type: 'boolean', default: false },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Timetable: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            classId: { type: 'string', format: 'uuid' },
            class: { $ref: '#/components/schemas/Class' },
            subjectId: { type: 'string', format: 'uuid' },
            subject: { $ref: '#/components/schemas/Subject' },
            teacherId: { type: 'string', format: 'uuid' },
            teacher: { $ref: '#/components/schemas/User' },
            room: { type: 'string' },
            dayOfWeek: { type: 'integer', minimum: 1, maximum: 7 },
            startTime: { type: 'string', format: 'time' },
            endTime: { type: 'string', format: 'time' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        AuditLog: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            user: { $ref: '#/components/schemas/User' },
            action: { type: 'string' },
            entity: { type: 'string' },
            entityId: { type: 'string' },
            details: { type: 'object' },
            ipAddress: { type: 'string' },
            userAgent: { type: 'string' },
            schoolId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        DashboardKPIs: {
          type: 'object',
          properties: {
            totalStudents: { type: 'integer' },
            totalTeachers: { type: 'integer' },
            attendanceRate: { type: 'integer' },
            collected: { type: 'number' },
            outstanding: { type: 'number' },
            avgGrade: { type: 'number' },
            totalExpected: { type: 'number' },
            totalCollected: { type: 'number' },
            totalOutstanding: { type: 'number' },
            collectionRate: { type: 'integer' },
          },
        },
        DashboardCharts: {
          type: 'object',
          properties: {
            revenueByMonth: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  month: { type: 'string' },
                  revenue: { type: 'number' },
                },
              },
            },
            attendanceByClass: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  status: { type: 'string' },
                  count: { type: 'integer' },
                },
              },
            },
            gradeDistribution: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  grade: { type: 'string' },
                  count: { type: 'integer' },
                },
              },
            },
            totalGrades: { type: 'integer' },
          },
        },
      },
    },
    security: [
      { bearerAuth: [] },
      { cookieAuth: [] },
    ],
    tags: [
      { name: 'Authentication', description: 'Authentication and user management' },
      { name: 'Students', description: 'Student management' },
      { name: 'Teachers', description: 'Teacher management' },
      { name: 'Classes', description: 'Class management' },
      { name: 'Subjects', description: 'Subject management' },
      { name: 'Grades', description: 'Grade management' },
      { name: 'Attendance', description: 'Attendance tracking' },
      { name: 'Fees', description: 'Fee management' },
      { name: 'Payments', description: 'Payment processing' },
      { name: 'Documents', description: 'Document management' },
      { name: 'Document Builder', description: 'Document template and generation' },
      { name: 'Report Cards', description: 'Report card generation' },
      { name: 'Timetable', description: 'Timetable management' },
      { name: 'Announcements', description: 'Announcements' },
      { name: 'Notifications', description: 'User notifications' },
      { name: 'Dashboard', description: 'Dashboard analytics' },
      { name: 'Settings', description: 'School settings' },
      { name: 'Audit Logs', description: 'Audit logging' },
      { name: 'Users', description: 'User management' },
      { name: 'Roles', description: 'Role and permission management' },
      { name: 'Parents', description: 'Parent management' },
      { name: 'Enrollment', description: 'Student enrollment' },
      { name: 'Discipline', description: 'Discipline management' },
      { name: 'Academic', description: 'Academic analytics' },
      { name: 'Finance', description: 'Financial analytics' },
      { name: 'Modules', description: 'Module management' },
      { name: 'Currencies', description: 'Currency management' },
      { name: 'Structure', description: 'Academic structure' },
      { name: 'Workspace', description: 'Workspace management' },
    ],
  },
  apis: ['./src/routes/*.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);